#!/bin/bash

TOTAL=$(ls -1 $IN_DIR | grep jpeg | wc -l)
START_TIME=$(date +%s)

HEAD=$(($TOTAL / 2))
TAIL=$(bc -l <<< "$TOTAL-$HEAD")

# orig -> no black -> largest dimension to end size -> crop to square
for f in $(ls $IN_DIR | grep jpeg);
do
	echo convert ${IN_DIR}/$f -fuzz 10% -trim \
		-scale ${OUT_SIZE}x${OUT_SIZE}^ \
		-gravity center -extent ${OUT_SIZE}x${OUT_SIZE} \
		-define jpeg:preserve-settings ${OUT_DIR}/$f;

done > "simple_crop_batch_$START_TIME.txt"

echo "run: gm batch -echo on -feedback on XXX"
echo "\n"
echo "head: $HEAD"
echo "tail: $TAIL"
echo "\n"
echo "simple_crop_batch_$START_TIME.txt"